name: Test

on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  rspec:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      fail-fast: true
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rspec
        run: |
          bundle exec rspec
